#!/usr/bin/env node
initBabel();

process.env.ENV = 'test';

const {execSync} = require('child_process');
const createDbFixtures = require('./dbFixtures').default;
const noInit = process.argv.slice(2).indexOf('noinit') !== -1;

//********************************************

if (noInit) {
    console.log('running tests without initing the test DB');
    runMocha();
} else {
    initDB();

    initFixtures()
        .then(runMocha)
        .catch(err => console.error(err));
}

//********************************************

function initBabel() {
    global.regeneratorRuntime = require('babel-regenerator-runtime');
    require("babel-register")({});
}

function initDB() {
    return execSync('DB=resonators_test ./scripts/initdb', {
        stdio: 'inherit'
    });
}

function initFixtures() {
    return createDbFixtures();
}

function runMocha() {
    return execSync('mocha --watch --require test/setup test/**/*.test.js', {
        stdio: 'inherit'
    });
}
