#!/usr/bin/env node
initTs();

process.env.ENV = 'test';

const {execSync} = require('child_process');
const createDbFixtures = require('./dbFixtures').default;
const args = process.argv.slice(2);
const noInit = args.indexOf('noinit') !== -1;

//********************************************

if (noInit) {
    console.log('running tests without initing the test DB');
    runMocha();
} else {
    initDB();

    initFixtures()
        .then(runMocha)
        .catch(err => console.error(err));
}

//********************************************

function initTs() {
    require('ts-node').register();
}

function initDB() {
    return execSync('DB=resonators_test ./scripts/initdb', {
        stdio: 'inherit'
    });
}

function initFixtures() {
    return createDbFixtures();
}

function runMocha() {
    const mochaArgsIdx = args.indexOf('--') + 1;
    let mochaArgsArr = [];

    if (mochaArgsIdx) {
        mochaArgsArr = args.slice(mochaArgsIdx);
    }

    const mochaArgs = mochaArgsArr.join(' ');

    const mochaCmd = `mocha --require test/setup test/before.test.js ${mochaArgs}`;

    return execSync(mochaCmd, {
        stdio: 'inherit'
    });
}
