#!/usr/bin/env node

const databases = [
    'resonators_dev',
    'resonators_test'
];

const exec = (...args) => require('child_process').execSync(...args, {stdio: 'inherit'});

console.log('***************\nDB SETUP\n***************\n');

databases.forEach(dbName => {
    console.log(`dropdb ${dbName}`);
    exec(`dropdb ${dbName} -U postgres --if-exists`);
    console.log(`createdb ${dbName}`);
    exec(`createdb ${dbName} -U postgres`);
});

console.log('\n***************\nDB MIGRATION\n***************\n');

const sequelize = args => './node_modules/.bin/sequelize ' + args;

exec(sequelize('db:migrate'));
