#!/bin/bash
[ -d ${GIT_WORK_TREE} ] || mkdir ${GIT_WORK_TREE}
GIT_WORK_TREE=../resonators-server
export GIT_WORK_TREE
git checkout -f
echo "==========  CODE DEPLOYED - INSTALLING =========="
cd ${GIT_WORK_TREE}
npm install
echo "==========  RESTARTING SERVER  =========="

npm run restart:prod || npm run start:prod

echo "==========  DONE  =========="
